### PR TITLE
BUGFIX: Replace GeneratorService by AfxTemplateGenerator

### PR DESCRIPTION
**Pull request by zickgraf**
Adapts to https://github.com/neos/neos-development-collection/pull/3089

### CODE REVIEW

**Review by bwaidelich — APPROVED** [review]
+1 by reading

Thank you!

**Review by markusguenther — APPROVED** [review]
Thanks for the fix.
Tested that with 7.0.1 and the patch works.

**Comment by markusguenther** [comment]
Screenshot 2020-12-28 at 19 39 47

Error when creating an own site package in step 3.

**Comment by kdambekalns** [comment]
This creates a regression, as Neos 5.3 will happily pull in the version having this (1.1.3) but ill not have the site kickstarter that provides the AFX generator service.

**Pull request merged**
