### PR TITLE
BUGFIX: Filter sites to import from

### PR DESCRIPTION
**Pull request by Sebobo**
This error appeared due to an parameter change in https://github.com/neos/flow-development-collection/commit/b0713d4cb705836df2861c30b4ae937e3bde5a0a

Resolves: #8

### CODE REVIEW

**Review by bwaidelich — COMMENTED** [review]
Good catch, we should be more careful when we change the signature of API methods – and we shouldn't do that in a patchlevel release anyways

But I wonder: This package is compatible with Neos `^5.0 || ^7.0 || ^8.0` and the signature changed only for 7.3.8+

**Review by kdambekalns — APPROVED** [review]
👍

**Comment by kitsunet** [comment]
What basti said, I guess I would revert the original change for now just to avoid splitting between versions. and reintroduce it as breaking change with 7.0

**Comment by kdambekalns** [comment]
> This package is compatible with Neos ^5.0 || ^7.0 || ^8.0 and the signature changed only for 7.3.8+

_Thou shalt not be using setup with old Neos versions these days…_

**Comment by Sebobo** [comment]
> Good catch, we should be more careful when we change the signature of API methods – and we shouldn't do that in a patchlevel release anyways
> 
> But I wonder: This package is compatible with Neos `^5.0 || ^7.0 || ^8.0` and the signature changed only for 7.3.8+

Oh thx! I didn't notice that dependency. Hmmm, shouldn't it be fine then to bump the dependency in this PR to `^7.3.8 || ^8.0`?

**Pull request merged**
